export const navToggle = document.querySelector('.nav-toggle');
export const navLinks = document.querySelector('.links');
export const movieDetail = document.querySelector('.box-container');
export const shownMovies = document.querySelector('.shown-movies');
export const movieCloseBtn = document.querySelector('#movie-close-btn');
export const reservationCloseBtn = document.querySelector('#close-reservation');
export const popupSection = document.querySelector('.popup-section');
export const reservationSection = document.querySelector('.reservation-section');
export const movieURL = 'https://api.tvmaze.com/search/shows?q=';